hello: world
foo: bar
config:
  name: cjdname
testers:  
  instructors:
  -
      name: "Chris Decelles"
      title: "Sr. Platform Architect"
      email: "cdeelles@pivotal.io"
      phone: "603.512.5616"
  -
      name: "Mark Fynes"
      title: "Advisory Platform Architect"
      email: "mark@pivotal.io"
      phone: "617.333.3333"
  
material:
  day1:
    -
      topicID: "ss1"
      timeDescription: "Sr. Platform Architect1"
  -
      topicID: "ss2"
      timeDescription: "Sr. Platform Architect2"
  day2
      -
      topicID: "ss3"
      timeDescription: "Sr. Platform Architect3"
  -
      topicID: "ss4"
      timeDescription: "Sr. Platform Architect3"

fortune:
  messages:
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
