--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

courseTitle: "Pivotal Cloud Foundry Workshop"
courseDate: "March 17 - 18, 2016"
courseDescription: "This workshop will cover the ..."

customerLogo: "https://workplace.fidelity.com/sites/default/files/fidelity_wps_logo.png"
workshop: 
  instructors: 
    - 
      name: "Chris Joseph Decelles"
      title: "Sr. Platform Architect"
      email: cdeelles@pivotal.io
      phone: "603.512.5616"
    - 
      name: "Mark Fynes"
      title: "Advisory Platform Architect"
      email: tfynesk@pivotal.io
      phone: "617.333.3333"
content:
  sessions:
    - 
      id: "day1"
      name: "Day 1"
      description: "Welcome to Day 1"
      topics:
      -
        id: "00-introduction"
        title: "tiel1"
        description: "tieldesc"
        slideURL: "slide url1"
      -
        id: "02-intro-to-pcf"
        title: "tiel2"
        description: "tieldesc2"
        slideURL: "slide ur2l"
    - 
      id: "day2"
      name: "Day 2"
      description: "Welcome to Day 2"
      topics:
      -
        id: "02-intro-to-pcf"
        title: "tiel1"
        description: "tieldesc"
        slideURL: "slide url1"
      -
        id: "02-intro-to-pcf"
        title: "tiel2"
        description: "tieldesc2"
        slideURL: "slide ur2l"
