config:
  name: liberty-mutual-ci
foo: bar
fortune:
  messages:
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop:
  contentURL: "https://workshop-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "December 14, 2016"
  description: "This workshop will cover the ..."
  customerLogo: "https://www.libertymutual.com/insurance-content/logos/liberty-mutual-insurance-facebook.gif"
  instructors:
    -
      name: "Chuck D'Antonio"
      title: "Advisory Platform Architect"
      email: cdantonio@pivotal.io
      phone: "(617) 388-1120"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    -
      id: "day1"
      name: "Workshop Sessions"
      description: "Content for December 14, 2016"
      topics:
      -
        id: "session3"
        title: "Cloud Native Applications"
      -
        id: "a-new-way-of-working"
        title: "A New Way of Working"
      -
        id: "why-cloud-native-slides"
      -
        id: "68-cloud-native-design"
      -
        id: "70-microservices"
      -
        id: "session1"
        title: "Application Development"
      -
        id: "08-deploy-simple-app"
      -
        id: "10-application-manifest"
      -
        id: "12-domains-and-routes"
      -
        id: "14-services"
      -
        id: "springboot"
        title: "Spring Boot"
      -
        id: "spring-boot-labs-setup"
      -
        id: "80-cs-spring-boot-basics"
      -
        id: "82-cs-spring-boot-adv"
      -
        id: "actuator"
      -
        id: "spring-data-rest"
      -
        id: "scs"
        title: "Spring Cloud Services"
      -
        id: "scs-labs-setup"
      -
        id: "config"
      -
        id: "service-discovery"
      -
        id: "circuit-breakers"
      -
        id: "datamicroservices"
        title: "Data Microservices"
      -
        id: "springcloud-dataflow"
