config:
  name: liberty-mutual-2017

workshop:
  contentURL: "https://workshop-content-crdant.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "Recurring Monthly"
  description: "<p>This workshop is targeted primarily at application developers who feel that
     something just isn’t working with the way they are working. Developing Cloud-Native applications and deploying
     them to CloudForge will help you and your team to deliver better software, faster, and with less hassle.</p>"
  customerLogo: "https://www.libertymutual.com/insurance-content/logos/liberty-mutual-insurance-facebook.gif"
  instructors:
    -
      name: "Chuck D'Antonio"
      title: "Advisory Platform Architect"
      email: "cdantonio@pivotal.io"
      phone: "(617) 388-1120"
    -
      name: "Scott Curry"
      title: "Developer Advocate"
      email: "scott.curry@libertymutual.com"
  resources:
    -
      title: "Preparing for the Workshop"
      url: "https://forge.lmig.com/wiki/display/STAC/CloudForge+Workshop+Prerequisites"
    -
      title: "Liberty Cloud Principles"
      url: "https://git.forge.lmig.com/projects/CLOUDFORGE/repos/cloud-principles/browse"
    -
      title: "Cloud-Native Enterprise"
      url: https://cf-presentations.sandbox.paas.lmig.com/cloud-native-enterprise/#/
    -
      title: "CloudForge Home"
      url: "https://forge.lmig.com/"
    -
      title: "CloudForge Portal"
      url: "https://cloudforge-portal.pdc.paas.lmig.com/#/pipeline"
    -
      title: "Installing the Cloud Foundry Command Line at Liberty"
      url: "https://forge.lmig.com/wiki/x/qQmjB"
    -
      title: "Liberty Commerical Insurance Cookbook"
      url: "https://pcf-cookbook.sandbox.paas.lmig.com/"
    -
      title: "Code Like a Rock Star!"
      url: "https://myvideo.lmig.com/viewerportal/video/video.vp?programId=esc_program%3A14946&contentAssocId=association%3A62435"
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    -
      id: "sessions"
      name: "Workshop Sessions"
      description: "Learning about Cloud Foundry, CloudForge, and Cloud Native Applications"
      topics:
      -
        id: "what-is-this-cloud-native-stuff"
        title: What is Cloud Native?
      -
        id: "cloud-native-applications"
      -
        id: "microservices-short"
      -
        id: "libertys-cloud-platform"
        title: Liberty's Cloud Native Platform
      -
        id: "what-is-cloudforge"
      -
        id: "emptysession"
        title: "The Platform for a New Way of Working"
      -
        id: "health-lab"
      -
        id: "conventions"
      -
        id: "more-reasons-cloudforge"
      -
        id: "cloud-native-architeture"
        title: Cloud Native Architecture
      -
        id: "12-factor-detailed"
      -
        id: "liberty-twelve-factor-quiz"
      -
        id: "cloudforge-services"
      -
        id: "cloudforge-security"
      -
        id: "curfew"
      -
        id: "becoming"
      -
        id: "liberty-cloud-adoption"
      -
        id: "appcontinuum"
      -
        id: "a-little-deeper"
        title: A Little Deeper
      -
        id: "emptysession"
        title: "A Look Inside Cloud Foundry"
      -
        id: "exploring-12-factors"
    -
      id: "videos"
      name: "Videos"
      description: "Liberty and Pivotal Video series"
      topics:
        -
          id: "ci-dojo-video"
        -
          id: "cio-diversification-video"
        -
          id: "cio-faster-video"
        -
          id: "cio-innovation-video"
        -
          id: "cio-partnerships-video"
        -
          id: "cio-trust-video"
        -
          id: "cio-urgency-video"
        -
          id: "ets-labs-video"
        -
          id: "gs-labs-video"
        -
          id: "labs-pairing-video"
