config:
  name: liberty-mutual-2017

workshop:
  contentURL: "https://workshop-content-crdant.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "Recurrding Monthly"
  description: "<p>This workshop is targeted primarily at application developers and their managers who feel that
     something just isn’t working with the way they are working. Developing Cloud-Native applications and Deploying
     them to CloudForge will help you and your team to deliver better software, faster, and with less hassle.</p>
     <p>We’ll steadily build the level of detail that we cover, providing opportunities for managers to learn about the
     broader themes while leaving the code-level topics for their teams. When we get into the details, we’ll be focusing on
     Java but touching on .NET and other languages as well.</p>"
  customerLogo: "https://www.libertymutual.com/insurance-content/logos/liberty-mutual-insurance-facebook.gif"
  instructors:
    -
      name: "Chuck D'Antonio"
      title: "Advisory Platform Architect"
      email: cdantonio@pivotal.io
      phone: "(617) 388-1120"
  resources:
    -
      title: "CloudForge Home"
      url: "https://forge.lmig.com/"
    -
      title: "CloudForge Portal"
      url: "https://cloudforge-portal.pdc.paas.lmig.com/#/pipeline"
    -
      title: "Liberty Commerical Insurance Cookbook"
      url: "https://pcf-cookbook.sandbox.paas.lmig.com/"
    -
      title: "Code Like a Rock Star!"
      url: "https://myvideo.lmig.com/viewerportal/video/video.vp?programId=esc_program%3A14946&contentAssocId=association%3A62435"
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    -
      id: "day1"
      name: "Workshop Sessions"
      description: "Content for December 14, 2016"
      topics:
      -
        id: "platform"
        title: "Cloud Native Platform"
      -
        id: "a-new-way-of-working"
        title: "A New Way of Working"
      -
        id: "cloudforge-overview"
        title: "The CloudForge Experience"
      -
        id: "sample-application"
      -
        id: "deploying-to-cloudforge"
        title: "Deploying with CloudForge"
      -
        id: "applications"
        title: "Cloud Native Applications"
      -
        id: "twelve-factor-apps-and-beyond"
        title: "12 Factor Applications (and Beyond)"
      -
        id: "api-first"
        title: "API First"
      -
        id: "design-for-failure"
        title: "Design for Failure"
      -
        id: "70-microservices"
        title: "Microservices"
      -
        id: "session1"
        title: "Developing Applications"
      -
        id: "spring-boot-labs-setup"
      -
        id: "80-cs-spring-boot-basics"
      -
        id: "82-cs-spring-boot-adv"
      -
        id: "actuator"
      -
        id: "14-services"
      -
        id: "spring-data-rest"
      -
        id: "advanced"
        title: "Advanced Topics"
      -
        id: "08-deploy-simple-app"
      -
        id: "10-application-manifest"
      -
        id: "12-domains-and-routes"
