--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop: 
  contentURL: "https://workshop-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "September 8-9, 2016"
  instructors: 
    - 
      name: "Chris Decelles"
      title: "Sr. Platform Architect"
      email: cdecelles@pivotal.io
      phone: "603.512.5616"
    - 
      name: "Ravi Jagannathan"
      title: "Platform Architect"
      email: rjagannathan@pivotal.io
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    - 
      id: "day1"
      name: "Day 1"
      description: "Content for September, 8"
      topics:
      -
        id: "session1"
        title: "Session 1: 9:00 AM - 9:45 AM"
      -
        id: "pcf101-session1-cne"
      -
        id: "session1lab"
        title: "Demo: 9:45 AM - 10:15 AM"
      -
        id: "emptysession"
        title: "Pushing your first app, Apps Manager"
      -
        id: "day1ambreak"
        title: "Break 10:15 AM - 10:30 AM"
      -
        id: "session2"
        title: "Session 2: 10:30 AM - 12:00 PM"
      -
        id: "pcf101-session2-arch-oper"
        title: "Pivotal Cloud Foundry Architecture and Containers"
      -
        id: "pcf101-session2-arch-oper"
        title: "Pivotal Cloud Foundry for Operators"
      -
        id: "day1Lunch"
        title: "Lunch 12:00 PM - 1:00 PM"
      -
        id: "session3"
        title: "Session 3: 1:00 PM - 1:30 PM"
      -
        id: "pcf101-session3-services"
        title: "Pivotal Cloud Foundry Services"
      -
        id: "day1labs"
        title: "Labs: 1:30 PM - 3:30 PM"
      -
        id: "pcf101-lab1"
      -
        id: "pcf101-lab2"
      -
        id: "pcf101-lab3"
      -
        id: "pcf101-lab4"
      -
        id: "day1pmbreak"
        title: "Break 3:30 PM - 3:45 PM"
      -
        id: "day1open"
        title: "Open Discussion: 3:45 PM - 5:00 PM"
      -
        id: "emptysession"
        title: "COTS / ERP / Packaged Software"
        slideURL: "COTS.pd"
      -
        id: "emptysession"
        title: "Cloud Management / Governance"
        slideURL: "COTS.pd"
      -
        id: "emptysession"
        title: "PCF / Bluemix"
        slideURL: "COTS.pd"
    - 
      id: "day2"
      name: "Day 2"
      description: "Content for September, 9"
      topics:
      -
        id: "session1"
        title: "Application Development"
      -
        id: "04-cli"
      -
        id: "06-org-space-user-role"
      -
        id: "08-deploy-simple-app"
      -
        id: "10-application-manifest"
      -
        id: "12-domains-and-routes"
      -
        id: "micro"
        title: "Continous Delivery and Cloud Native Apps"
      -
        id: "66-continuous-delivery"
      -
        id: "68-cloud-native-design"
      -
        id: "70-microservices"
      -
        id: "springboot"
        title: "Spring Boot"
      -
        id: "80-cs-spring-boot-basics"
      -
        id: "82-cs-spring-boot-adv"
      -
        id: "scs"
        title: "Spring Cloud"
      -
        id: "config"
      -
        id: "service-discovery"
      -
        id: "circuit-breakers"
      -
        id: "security"
        title: "Security"
      -
        id: "59-oauth-primer"
      -
        id: "60-security-and-sso"

