config:
  name: boston-scientific

workshop:
  contentURL: "https://workshop-content-crdant.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "April 7, 2017"
  description: |
     <p>This workshop is targeted at developers and their managers who want to understand how a cloud-native approach
     changes the rules for enterprise integration. New development approaches and architecture shift the focus of an intergration
     team and enable new services models.</p>

     <p>We’ll steadily build the level of detail that we cover, providing opportunities for managers to learn about the broader themes
     while leaving the code-level topics for their teams. When we get into the details, we’ll be focusing on Java but touching on
     other languages as well.</p>
  customerLogo: "http://solar.schneider-electric.com/wp-content/uploads/2016/04/Schneider_Electric.svg_.png"
  instructors:
    -
      name: "Chuck D'Antonio"
      title: "Advisory Platform Architect"
      email: cdantonio@pivotal.io
      phone: "(617) 388-1120"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Spring Cloud Stream Initializr"
      url: "http://start-scs.cfapps.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    -
      id: "briefing"
      name: "Briefing"
      description: |
         This workshop is targeted at developers and their managers who want to understand how a cloud-native approach
         changes the rules for enterprise technology. We'll discuss the nature of cloud-native applications and how becoming
         cloud-native affects not only your applications but they way you build them and even how you structure your
         organization.
      topics:
      -
        id: "cloud-native-applications"
        title: "Cloud Native Applications"
      -
        id: "a-new-way-of-working"
        title: "A New Way of Working"
      -
        id: "what-is-cloud-native"
        title: "What is a Cloud-Native Application?"
      -
        id: "becoming-cloud-native"
        title: "How to Be(come) Cloud-Native"
      -
        id: "enabling-cloud-native"
        title: "Enabling A Cloud-Native Organization"
    -
      id: "workshop"
      name: "Workshop"
      description: |
         This workshop is targeted at developers and operators who will be working with Cloud Foundry as part of developing and
         operating applications. We will be working hands-on with Cloud Foundry and various Spring components that help you
         develop cloud-native applications in Java.
      topics:
      -
        id: "pivotal-cloud-foundry-section"
        title: "Pivotal Cloud Foundry"
      -
        id: "pcf-developer-push"
      -
        id: "pcf-developer-logging-scale-ha"
      -
        id: "pcf-developer-services"
      -
        id: "pcf-developer-buildpacks"
      -
        id: "pcf-developer-manifests"
      -
        id: "continuous-delivery-section"
        title: "Continous Delivery"
      -
        id: "pcf-developer-cd"
      -
        id: "blue-green-deployments"
        title: "Blue Green Deployment"
      -
        id: "boot"
        title: "Spring Boot"
      -
        id: "80-cs-spring-boot-basics"
        title: "Basics"
      -
        id: "82-cs-spring-boot-adv"
        title: "Advanced Features"
      -
        id: "actuator"
        title: "Actuator"
      -
        id: "scdf"
        title: "Spring Cloud Dataflow"
      -
        id: "02-architecture"
        title: "Architecture"
      -
        id: "04-introduction-streams"
        title: "Streams"
      -
        id: "09-spring-cloud-tasks"
        title: "Tasks"
