config:
  name: liberty-mutual-ci
foo: bar
fortune:
  messages:
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop:
  contentURL: "https://workshop-content-crdant.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "December 14, 2016"
  description: "This workshop will cover the ..."
  customerLogo: "https://s3.amazonaws.com/filecache.drivetheweb.com/mr5mr_bostonscientific/171609/BostonScientificBlue.jpg"
  instructors:
    -
      name: "Chuck D'Antonio"
      title: "Advisory Platform Architect"
      email: cdantonio@pivotal.io
      phone: "(617) 388-1120"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Spring Cloud Stream Initializr"
      url: "http://start-scs.cfapps.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    -
      id: "day1"
      name: "Workshop Sessions"
      description: "Content for April 7, 2017"
      topics:
      -
        id: "cloud-native-applications"
        title: "Cloud Native Applications"
      -
        id: "a-new-way-of-working"
        title: "A New Way of Working"
      -
        id: "what-is-cloud-native"
        title: "What is a Cloud-Native Application?"
      -
        id: "becoming-cloud-native"
        title: "How to Be(come) Cloud-Native"
      -
        id: "pivotal-cloud-foundry-section"
        title: "Pivotal Cloud Foundry"
      -
        id: '02-intro-to-pcf'
      -
        id: "08-deploy-simple-app"
      -
        id: '26-elastic-runtime'
      -
        id: "62-buildpacks"
      -
        id: "14-services"
      -
        id: "58-service-broker"
      -
        id: "monitoring-logging"
      -
        id: "security-topics"
      -
        id: "scdf"
        title: "Spring Cloud Dataflow"
      -
        id: "data-microservices-pcf"
        title: "Data Microservices"
      -
        id: "02-architecture"
        title: "Architecture"
      -
        id: "04-introduction-streams"
        title: "Streams"
      -
        id: "05-advanced-streams"
        title: "Advanced Streams"
      -
        id: "09-spring-cloud-tasks"
        title: "Tasks"
