config:
  name: dellemc
foo: bar
fortune:
  messages:
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop:
  contentURL: "https://workshop-content.cfapps.io"
  title: "DellEMC Cloud Native Workshop"
  date: "December 12, 2016"
  description: "Go big!"
  customerLogo: "http://brand.emc.com/dellbrand/wp-content/uploads/2016/05/DellEMC_Logo_Hz_Blue_Gry_rgb-500x89.png"
  instructors:
    -
      name: "Chuck D'Antonio"
      title: "Advisory Platform Architect"
      email: "cdantonio@pivotal.io"
      phone: "+1 617 388 1120"
    -
      name: "Ravi Jagannathan"
      title: "Platform Architect"
      email: "rjagannathan@pivotal.io"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    -
      id: "workshop"
      name: "Workshop Sessions"
      description: "Content for one-day workshop December 12, 2016"
      topics:
      -
        id: "architecture"
        title: "Architecture and Process"
      -
        id: "day1ambreak"
        title: "Break 10:15 AM - 10:30 AM"
      -
        id: "design"
        title: "Design Principles and Patterns"
      -
        id: "implementation"
        title: "Accelerating Implementation"
      -
        id: "day1Lunch"
        title: "Lunch 12:00 PM - 1:00 PM"
      -
        id: "getting-started"
        title: "Getting Started"
