config:
  name: liberty-mutual-2017

workshop:
  contentURL: "https://workshop-content-crdant.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "Recurring Monthly"
  description: "<p>This workshop is targeted primarily at application developers and their managers who feel that
     something just isn’t working with the way they are working. Developing Cloud-Native applications and Deploying
     them to CloudForge will help you and your team to deliver better software, faster, and with less hassle.</p>
     <p>We’ll steadily build the level of detail that we cover, providing opportunities for managers to learn about the
     broader themes while leaving the code-level topics for their teams. When we get into the details, we’ll be focusing on
     Java but touching on .NET and other languages as well.</p>"
  customerLogo: "https://www.libertymutual.com/insurance-content/logos/liberty-mutual-insurance-facebook.gif"
  instructors:
    -
      name: "Chuck D'Antonio"
      title: "Advisory Platform Architect"
      email: cdantonio@pivotal.io
      phone: "(617) 388-1120"
  resources:
    -
      title: "Liberty Cloud Principles"
      url: "https://git.forge.lmig.com/projects/CLOUDFORGE/repos/cloud-principles/browse"
    -
      title: "Cloud-Native Enterprise"
      url: https://cf-presentations.sandbox.paas.lmig.com/cloud-native-enterprise/#/
    -
      title: "CloudForge Home"
      url: "https://forge.lmig.com/"
    -
      title: "CloudForge Portal"
      url: "https://cloudforge-portal.pdc.paas.lmig.com/#/pipeline"
    -
      title: "Liberty Commerical Insurance Cookbook"
      url: "https://pcf-cookbook.sandbox.paas.lmig.com/"
    -
      title: "Code Like a Rock Star!"
      url: "https://myvideo.lmig.com/viewerportal/video/video.vp?programId=esc_program%3A14946&contentAssocId=association%3A62435"
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    -
      id: "day1"
      name: "Workshop Sessions"
      description: "Learning about Cloud Foundry, CloudForge, and Spring Boot"
      topics:
      -
        id: "platform"
        title: "Cloud Native Platform"
      -
        id: "the-platform-for-a-new-way-of-working"
        title: "The Platform for A New Way of Working"
      -
        id: "emptysession"
        title: "Cloud Native Application Demo"
      -
        id: "cio-faster-video"
      -
        id: "the-cloud-forge-platform"
        title: "CloudForge"
      -
        id: "cloudforge-overview"
        title: "The CloudForge Experience"
      -
        id: "sample-application"
        title: "A Sample Cloud-Native Application"
      -
        id: "cloud-native-applications"
        title: "Cloud-Native Applications"
      -
        id: "cloud-native-application"
        title: "What is a Cloud-Native Application?"
      -
        id: "liberty-twelve-factor-quiz"
        title: "A Quiz in Twelve Factors"
      -
        id: "ci-dojo-video"
      -
        id: "becoming-cloud-native"
        title: "How to Be(come) Cloud-Native"
      -
        id: "emptysession"
        title: "A Pair Programming Experience"
      -
        id: "session1"
        title: "Developing Applications"
      -
        id: "gs-labs-video"
      -
        id: "deploying-to-cloudforge"
        title: "Deploying with CloudForge"
      -
        id: "cloudforge-services"
        title: "Cloud Forge Services"
      -
        id: "cloudforge-bluegreen"
        title: "Blue-Green Deployment with CloudForge"
      -
        id: "cloudforge-network-access"
        title: "Security on CloudForge"
      -
        id: "advanced"
        title: "Advanced Topics"
      -
        id: "pcf-developer-logging-scale-ha"
        title: "A Look Inside Cloud Foundry"
    -
      id: "appendix"
      name: "Additional Material"
      description: "Additional supporting material for the workshop"
      topics:
      -
        id: "architecture-and-design"
        title: "Cloud-Native Techniques"
      -
        id: "twelve-factor-apps-and-beyond"
        title: "12 Factor Applications (and Beyond)"
      -
        id: "api-first"
        title: "API First"
      -
        id: "design-for-failure"
        title: "Design for Failure"
      -
        id: "70-microservices"
        title: "Microservices"
      -
        id: "pivotal-cloud-foundry-intro"
        title: "Pivotal Cloud Foundry"
      -
        id: "02-intro-to-pcf"
        title: "Overview"
      -
        id: "04-cli"
        title: "The cf Command Line"
      -
        id: "06-org-space-user-role"
        title: "Orgs, Spaces, Users, and Roles"
      -
        id: "10-application-manifest"
        title: "Application Manifests"
      -
        id: "12-domains-and-routes"
        title: "Domains and Routes"
      -
        id: "14-services"
        title: "Services"
    -
      id: "videos"
      name: "Videos"
      description: "Liberty and Pivotal Video series"
      topics:
        -
          id: 'ci-dojo-video'
        -
          id: 'cio-diversification-video'
        -
          id: 'cio-faster-video'
        -
          id: 'cio-innovation-video'
        -
          id: 'cio-partnerships-video'
        -
          id: 'cio-trust-video'
        -
          id: 'cio-urgency-video'
        -
          id: 'ets-labs-video'
        -
          id: 'gs-labs-video'
        -
          id: 'labs-pairing-video'
