--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop: 
  contentURL: "https://workshop-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "August 16, 2016"
  description: "This workshop will cover the ..."
  customerLogo: "http://www.johnhancock.com/resources/images/common/john-hancock-logo.gif"
  instructors: 
    - 
      name: "Chris Decelles"
      title: "Sr. Platform Architect"
      email: cdecelles@pivotal.io
      phone: "603.512.5616"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    - 
      id: "day1"
      name: "August 16"
      description: "Content for August, 16"
      topics:
      -
        id: "02-intro-to-pcf"
      -
        id: "04-cli"
      -
        id: "06-org-space-user-role"
      -
        id: "08-deploy-simple-app"
      -
        id: "10-application-manifest"
      -
        id: "14-services"
      -
        id: "micro"
        title: "Microservices"
      -
        id: "68-cloud-native-design"
      -
        id: "70-microservices"
      -
        id: "springboot"
        title: "Spring Boot"
      -
        id: "80-cs-spring-boot-basics"
      -
        id: "82-cs-spring-boot-adv"
      -
        id: "scs"
        title: "Spring Cloud"
      -
        id: "config"
      -
        id: "service-discovery"
      -
        id: "circuit-breakers"
      -
        id: "security"
        title: "Security"
      -
        id: "59-oauth-primer"
      -
        id: "60-security-and-sso"
