--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop: 
  contentURL: "https://workshop-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "September 8-9, 2016"
  description: "This workshop will cover the ..."
  customerLogo: "http://investor.citizensbank.com/~/media/Images/C/CitizensBank-IR/logo/logo.png?h=88&la=en&w=316"
  instructors: 
    - 
      name: "Chris Decelles"
      title: "Sr. Platform Architect"
      email: cdecelles@pivotal.io
      phone: "603.512.5616"
    - 
      name: "Ravi J."
      title: "Platform Architect"
      email: ravi@pivotal.io
      phone: "603.512.5616"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    - 
      id: "day1"
      name: "Day 1"
      description: "Content for September, 8"
      topics:
      -
        id: "session1"
        title: "9:00 AM - 9:45 AM"
      -
        id: "02-intro-to-pcf"
        title: "Welcome to the Cloud Native Enterprise"
      -
        id: "session1lab"
        title: "9:45 AM - 10:15 AM"
      -
        id: "04-cli"
        title: "Demo: Pushing your first app, Apps Manager"
      -
        id: "day1ambreak"
        title: "Break 10:15 AM - 10:30 AM"
      -
        id: "session2"
        title: "Break 10:30 AM - 12:00 PM"
      -
        id: "06-org-space-user-role"
        title: "Pivotal Cloud Foundry Architecture and Containers"
      -
        id: "08-deploy-simple-app"
        title: "Pivotal Cloud Foundry for Operators"
      -
        id: "day1Lunch"
        title: "Lunch 12:00 PM - 1:00 PM"
      -
        id: "session3"
        title: "1:00 PM - 1:30 PM"
      -
        id: "10-application-manifest"
        title: "Session 3: Pivotal Cloud Foundry Services"
      -
        id: "day1labs"
        title: "Labs 1:30 PM - 3:30 PM"
      -
        id: "14-services"
        title: "Labs - Push, Scale, Bind and Monitor your app"
      -
        id: "day1pmbreak"
        title: "Break 3:30 PM - 3:45 PM"
    - 
      id: "day2"
      name: "Day 2"
      description: "Content for September, 9"
      topics:
      -
        id: "session1"
        title: "Session 1"
      -
        id: "02-intro-to-pcf"
      -
        id: "04-cli"
      -
        id: "06-org-space-user-role"
      -
        id: "08-deploy-simple-app"
      -
        id: "10-application-manifest"
      -
        id: "14-services"
      -
        id: "micro"
        title: "Microservices"
      -
        id: "68-cloud-native-design"
      -
        id: "70-microservices"
      -
        id: "springboot"
        title: "Spring Boot"
      -
        id: "80-cs-spring-boot-basics"
      -
        id: "82-cs-spring-boot-adv"
      -
        id: "scs"
        title: "Spring Cloud"
      -
        id: "config"
      -
        id: "service-discovery"
      -
        id: "circuit-breakers"
      -
        id: "security"
        title: "Security"
      -
        id: "59-oauth-primer"
      -
        id: "60-security-and-sso"

