config:
  name: dellemc

workshop:
  contentURL: "https://workshop-content-crdant.cfapps.io"
  title: "Becoming Cloud Native"
  date: "December 12, 2016"
  description: "<p>This workshop is targeted primarily at application developers and their managers who feel that
     something just isn’t working with the way they are working. If your group is producing applications or services that
     run on the Internet or on our internal network, this session will teach you techniques to build and deploy faster
     and deliver what you build more quickly.</p>

     <p>We’ll steadily build the level of detail that we cover, providing opportunities for managers to learn about the
     broader themes while leaving the code-level topics for their teams. When we get into the details, we’ll be focusing on
     Java but touching on .NET and other languages as well.</p>"
  customerLogo: "http://brand.emc.com/dellbrand/wp-content/uploads/2016/05/DellEMC_Logo_Hz_Blue_Gry_rgb-500x89.png"
  instructors:
    -
      name: "Chuck D'Antonio"
      title: "Advisory Platform Architect"
      email: "cdantonio@pivotal.io"
      phone: "+1 617 388 1120"
    -
      name: "Ravi Jagannathan"
      title: "Platform Architect"
      email: "rjagannathan@pivotal.io"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    -
      id: "workshop"
      name: "Workshop Session"
      description: "Becoming Cloud Native with DellEMC IT Cloud Foundry"
      topics:
        -
          id: "executive-open"
          title: "Executive Open"
        -
          id: "architecture"
          title: "Architecture and Process"
        -
          id: "a-new-way-of-working"
          title: "A New Way of Working"
        -
          id: "an-open-ecosystem-of-services"
          title: "An Open Ecosystem of Services"
        -
          id: "coming-soon"
          title: "Live Coding!"
        -
          id: "design"
          title: "Design Principles and Patterns"
        -
          id: "coming-soon"
          title: "Design for Failure"
        -
          id: "coming-soon"
          title: "API First"
        -
          id: "twelve-factor-apps"
          title: "12 Factor Applications"
        -
          id: "coming-soon"
          title: "Beyond the 12 Factors"
        -
          id: "70-microservices"
          title: "Microservices"
        -
          id: "data-microservices"
          title: "Data Microservices"
        -
          id: "implementation"
          title: "Accelerating Implementation"
        -
          id: "80a-cs-spring-boot-condensed"
          title: "Spring Boot"
        -
          id: "66-continuous-delivery"
          title: "Continuous Delivery"
        -
          id: "pcf101-session1-cne"
          title: "Pivotal Cloud Foundry"
        -
          id: "coming-soon"
          title: "DellEMC IT Cloud Foundry"
        -
          id: "85a-spring-cloud-condensed"
          title: "Spring Cloud Services"
        -
          id: "springcloud-dataflow"
          title: "Spring Cloud Data Flow"
        -
          id: "coming-soon"
          title: "Steeltoe"
        -
          id: "getting-started"
          title: "Getting Started"
        -
          id: "coming-soon"
          title: "New Applications"
        -
          id: "legacy-migration-to-cloud"
          title: "Existing Applications"
        -
          id: "coming-soon"
          title: "Leveraging DellEMC IT Cloud Foundry"
    -
      id: "selfstudylabs"
      name: "Labs for Self Study"
      description: "Lab exercises to get you started"
      topics:
        -
          id: "springboot"
          title: "Spring Boot"
        -
          id: "spring-boot-labs-setup"
          title: "Spring Boot Lab Setup"
        -
          id: "80-cs-spring-boot-basics"
          title: "Spring Boot Basics"
        -
          id: "82-cs-spring-boot-adv"
          title: "Spring Boot Advanced"
        -
          id: "actuator"
          title: "Spring Boot Actuator"
        -
          id: "scs"
          title: "Spring Cloud Services"
        -
          id: "scs-labs-setup"
          title: "Spring Cloud Services Lab Setup"
        -
          id: "config"
          title: "Configuration Server"
        -
          id: "service-discovery"
          title: "Service Discovery"
        -
          id: "circuit-breakers"
          title: "Circuit Breakers"
