--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop: 
  hostURL: "https://cdn.enablement.pivotal.io/cna16/agenda"
  title: "Pivotal Cloud Foundry Workshop"
  date: "March 17 - 18, 2016"
  description: "This workshop will cover the ..."
  customerLogo: "https://workplace.fidelity.com/sites/default/files/fidelity_wps_logo.png"
  instructors: 
    - 
      name: "Chris Joseph Decelles"
      title: "Sr. Platform Architect"
      email: cdeelles@pivotal.io
      phone: "603.512.5616"
    - 
      name: "Mark Fynes"
      title: "Advisory Platform Architect"
      email: tfynesk@pivotal.io
      phone: "617.333.3333"
  sessions:
    - 
      id: "day1"
      name: "Day 1"
      description: "Welcome to Day 1"
      topics:
      -
        id: "00-introduction"
      -
        id: "02-intro-to-pcf"
    - 
      id: "day2"
      name: "Day 2"
      description: "Welcome to Day 2"
      topics:
      -
        id: "60-security-and-sso"
      -
        id: "62-buildpacks"
