--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

courseTitle: "Pivotal Cloud Foundry Workshop"
courseDate: "March 17 - 18, 2016"
courseDescription: "This workshop will cover the ..."

customerLogo: "https://workplace.fidelity.com/sites/default/files/fidelity_wps_logo.png"
testers: 
  instructors: 
    - 
      name: "Chris Joseph Decelles"
      title: "Sr. Platform Architect"
      email: cdeelles@pivotal.io
      phone: "603.512.5616"
    - 
      name: "Mark Fynes"
      title: "Advisory Platform Architect"
      email: tfynesk@pivotal.io
      phone: "617.333.3333"

material: 
  day1: 
    - 
      topicID: "00-introduction"
      timeDescription: "9:30 - 11:30"

    - 
      topicID: "02-intro-to-pcf"
      timeDescription: "1:00 - 5:00"
      title: "CJD's PCF Overview"

  day2: 
    - 
      topicID: "04-cli"
      timeDescription: "8:30 - 11:00"

    - 
      topicID: "06-lab-org-space-user-role"
      timeDescription: "11:30 - 1:00"


