hello: world
foo: bar
config:
  name: cjdname
  
instructors:
  instructor1:
    name: "Chris Decelles"
    title: "Sr. Platform Architect"
    email: "cdeelles@pivotal.io"
    phone: "603.512.5616"
  instructor2:
    name: "Mark Fynes"
    title: "Advisory Platform Architect"
    email: "mark@pivotal.io"
    phone: "617.333.3333"
  
fortune:
  messages:
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
