config:
  name: dellemc

workshop:
  contentURL: "https://workshop-content-crdant.cfapps.io"
  title: "Becoming Cloud Native"
  date: "December 12, 2016"
  description: "<p>This workshop is targeted primarily at application developers and their managers who feel that
     something just isn’t working with the way they are working. If your group is producing applications or services that
     run on the Internet or on our internal network, this session will teach you techniques to build and deploy faster
     and deliver what you build more quickly.</p>

     <p>We’ll steadily build the level of detail that we cover, providing opportunities for managers to learn about the
     broader themes while leaving the code-level topics for their teams. When we get into the details, we’ll be focusing on
     Java but touching on .NET and other languages as well.</p>"
  customerLogo: "http://brand.emc.com/dellbrand/wp-content/uploads/2016/05/DellEMC_Logo_Hz_Blue_Gry_rgb-500x89.png"
  instructors:
    -
      name: "Chuck D'Antonio"
      title: "Advisory Platform Architect"
      email: "cdantonio@pivotal.io"
      phone: "+1 617 388 1120"
    -
      name: "Ravi Jagannathan"
      title: "Platform Architect"
      email: "rjagannathan@pivotal.io"
  resources:
    -
      title: "The Application Continuum"
      url: "http://www.appcontinuum.io/"
    -
      title: "Twelve Factor Applications"
      url: "https://12factor.net"
    -
      title: "API First"
      url: "http://www.api-first.com/"
    -
      title: "Countainers and Pivotal Cloud Foundry"
      url: "https://d1fto35gcfffzn.cloudfront.net/platform/white-paper/Containers-and-Pivotal-Cloud-Foundry.pdf"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    -
      id: "workshop"
      name: "Workshop Session"
      description: "Becoming Cloud Native with DellEMC IT Cloud Foundry"
      topics:
        -
          id: "architecture"
          title: "What is Cloud Native?"
        -
          id: "a-new-way-of-working-dell"
          title: "A New Way of Working"
        -
          id: "an-open-ecosystem-of-services"
          title: "An Open Ecosystem of Services"
        -
          id: "cloud-native-architecture"
          title: "Cloud Native Architecture"
        -
          id: "design"
          title: "Cloud Native Principles and Patterns"
        -
          id: "design-for-failure"
          title: "Design for Failure"
        -
          id: "api-first"
          title: "API First"
        -
          id: "twelve-factor-apps-and-beyond"
          title: "12 Factor Applications (and Beyond)"
        -
          id: "70-microservices"
          title: "Microservices"
        -
          id: "data-microservices"
          title: "Data Microservices"
        -
          id: "implementation"
          title: "Accelerating Cloud Native Implementations"
        -
          id: "80a-cs-spring-boot-condensed"
          title: "Spring Boot"
        -
          id: "66-continuous-delivery"
          title: "Continuous Delivery"
        -
          id: "pcf101-session2-arch"
          title: "Pivotal Cloud Foundry"
        -
          id: "85a-spring-cloud-condensed"
          title: "Spring Cloud Services"
        -
          id: "springcloud-dataflow"
          title: "Spring Cloud Data Flow"
        -
          id: "steeltoe-and-dotnet"
          title: ".NET and Steeltoe"
        -
          id: "getting-started"
          title: "Becoming Cloud Native"
        -
          id: "new-applications"
          title: "New Applications"
        -
          id: "legacy-migration-to-cloud"
          title: "Existing Applications"
        -
          id: "dell-it-cloud-foundry"
          title: "Leveraging Dell IT Cloud Foundry"
    -
      id: "selfstudylabs"
      name: "Labs for Self Study"
      description: "Lab exercises to get you started"
      topics:
        -
          id: "springboot"
          title: "Spring Boot"
        -
          id: "spring-boot-labs-setup"
          title: "Spring Boot Lab Setup"
        -
          id: "80-cs-spring-boot-basics"
          title: "Spring Boot Basics"
        -
          id: "82-cs-spring-boot-adv"
          title: "Spring Boot Advanced"
        -
          id: "actuator"
          title: "Spring Boot Actuator"
        -
          id: "scs"
          title: "Spring Cloud Services"
        -
          id: "scs-labs-setup"
          title: "Spring Cloud Services Lab Setup"
        -
          id: "config"
          title: "Configuration Server"
        -
          id: "service-discovery"
          title: "Service Discovery"
        -
          id: "circuit-breakers"
          title: "Circuit Breakers"
