--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop: 
  contentURL: "https://cdn.enablement.pivotal.io/cna16/agenda"
  title: "Pivotal Cloud Foundry Workshop"
  date: "August 16 - 17, 2016"
  description: "This workshop will cover the ..."
  customerLogo: "http://www.johnhancock.com/resources/images/common/john-hancock-logo.gif"
  customerLogo1: "https://workplace.fidelity.com/sites/default/files/fidelity_wps_logo.png"
  instructors: 
    - 
      name: "Chris Decelles"
      title: "Sr. Platform Architect"
      email: cdecelles@pivotal.io
      phone: "603.512.5616"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    - 
      id: "day1"
      name: "Day 1"
      description: "Welcome to Day 1"
      topics:
      -
        id: "00-introduction"
      -
        id: "02-intro-to-pcf"
        description: "CJD PCF Rules"
    - 
      id: "day2"
      name: "Day 2"
      description: "Welcome to Day 2"
      topics:
      -
        id: "60-security-and-sso"
      -
        id: "62-buildpacks"
