---
config:
  name: cjdname
foo: bar
fortune:
  messages:
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop:
  contentURL: "https://workshop-content-crdant.cfapps.io"
  title: "Spring Cloud Workshop"
  date: "February 28-March 1, 2017"
  instructors:
    -
      name: "Chuck D'Antonio"
      title: "Advisory Platform Architect"
      email: cdantonio@pivotal.io
      phone: "+1 617.388.1120"
    -
      name: "Ravi Jagannathan"
      title: "Platform Architect"
      email: "rjagannathan@pivotal.io"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Spring Cloud Stream Initializr"
      url: "http://start-scs.cfapps.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    -
      id: "day1"
      name: "Day One - Spring Cloud"
      description: "Workshop content for Februrary 28"
      topics:
      -
        id: "springboot"
        title: "Spring Boot"
      -
        id: "spring-boot-labs-setup"
      -
        id: "80-cs-spring-boot-basics"
      -
        id: "82-cs-spring-boot-adv"
      -
        id: "actuator"
      -
        id: "spring-data-rest"
      -
        id: "scs"
        title: "Spring Cloud"
      -
        id: "design-for-failure"
      -
        id: "scs-labs-setup"
      -
        id: "config"
      -
        id: "service-discovery"
      -
        id: "client-slide-load-balancing"
      -
        id: "circuit-breakers"
      -
        id: "circuit-breaker-metric-aggregation"
    -
      id: "day2"
      name: "Day Two - Spring Cloud Dataflow"
      description: "Workshop content for March 1"
      topics:
      -
        id: "datamicroservices"
        title: "Data Microservices"
      -
        id: "02-architecture"
      -
        id: "04-introduction-streams"
        title: "Streams"
      -
        id: "05-advanced-streams"
        title: "Advanced Streams"
      -
        id: "09-spring-cloud-tasks"
        title: "Tasks"
      -
        id: "11-high-availability"
        title: "High Availability"
      -
        id: "12-management-monitoring"
        title: "Management and Monitoring"
