config:
  name: dellemc
foo: bar
fortune:
  messages:
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop:
  contentURL: "https://workshop-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "September 8-9, 2016"
  instructors:
    -
      name: "Chuck D'Antonio"
      title: "Advisory Platform Architect"
      email: cdantonio@pivotal.io
      phone: ""+1 617 388 1120"
    -
      name: "Ravi Jagannathan"
      title: "Platform Architect"
      email: rjagannathan@pivotal.io
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    -
      id: "workshop"
      name: "Workshop Sessions"
      description: "Content for one-day workshop December 12, 2016"
      topics:
      -
        id: "session1"
        title: "Cloud Native Enterprise"
      -
        id: "pcf101-session1-cne"
      -
        id: "session1lab"
        title: "Demo: 9:45 AM - 10:15 AM"
      -
        id: "emptysession"
        title: "Pushing your first app, Apps Manager"
      -
        id: "day1ambreak"
        title: "Break 10:15 AM - 10:30 AM"
      -
        id: "session2"
        title: "PCF Architecture and Operations"
      -
        id: "pcf101-session2-arch"
      -
        id: "pcf101-session2a-oper"
      -
        id: "day1Lunch"
        title: "Lunch 12:00 PM - 1:00 PM"
      -
        id: "pcf101-session3-services"
        title: "Pivotal Cloud Foundry Services"
      -
        id: "micro"
        title: "Continous Delivery and Cloud Native Apps"
      -
        id: "66-continuous-delivery"
      -
        id: "68-cloud-native-design"
      -
        id: "70-microservices"
      -
        id: "security"
        title: "Security"
      -
        id: "59-oauth-primer"
      -
        id: "60-security-and-sso"
      -
        id: "day1pmbreak"
        title: "Break 3:30 PM - 3:45 PM"
      -
        id: "day1open"
        title: "Open Discussions:"
      -
        id: "56-cloud-controller-API"
      -
        id: "58-service-broker"
      -
        id: "62-buildpacks"
      -
        id: "emptysession"
        title: "COTS / ERP / Packaged Software"
