---
config:
  name: cjdname
foo: bar
fortune:
  messages:
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop:
  contentURL: "https://workshop-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "September 8-9, 2016"
  instructors:
    -
      name: "Chuck D'Antonio"
      title: "Advisory Platform Architect"
      email: cdantonio@pivotal.io
      phone: "+1 617.388.1120"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    -
      id: "sessions"
      name: "Workshop Sessions"
      description: "Content for February 14, 2017"
      topics:
      -
        id: "features"
        title: "Features of a Modern Messaging Platform"
      -
        id: "a-new-way-of-working"
        title: "Distributed Design"
      -
        id: "cloud-native-architecture"
        title: "Reactive Processing"
      -
        id: "data-microservices"
        title: "Microservices Architecture"
      -
        id: "availabilit"
        title: "High Availability and Resiliency"
      -
        id: "40-high-availability"
        title: "Restore, Restart, Recreate"
      -
        id: "monitoring-logging"
        title: "Monitoring and Logging"
      -
        id: "distributed-scale"
        title: "Distributed Scale"
      -
        id: "security"
        title: "Security and Administration"
      -
        id: "security-topics"
        title: "The Three Rs and Other Security Features"
      -
        id: "patching-upgrading"
        title: "Patching and Upgrading"
      -
        id: "66-continuous-delivery"
        title: "Continuous Delivery"
      -
        id: "extending"
        title: "Extending the Platform"
      -
        id: "design-for-failure"
        title: "Cloud Services"
      -
        id: "intro-streams"
        title: "Sources, Sinks, and Streams"
